# Generated by Django 5.1.1 on 2024-10-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bussines_central', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='dumes/')),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'T006Documento',
            },
        ),
    ]
