# Generated by Django 5.1.1 on 2024-11-08 21:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bussines_central', '0003_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='numeros_sugeridos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
