# Generated by Django 5.1.1 on 2024-11-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bussines_central', '0004_match_numeros_sugeridos'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
